name: alcs
channels:
  - defaults
dependencies:
  - gym
  - numpy
  - matplotlib
  - statistics
  - ray-default
  - ray-dashboard
  - pandas
  - networkx
  - notebook
  - jupyter_contrib_nbextensions
  - nbconvert=5.6.1
  - tornado=6.1
  - seaborn
  - statsmodels
variables:
  PYTHONHASHSEED: '0'
